apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: proxycontainer
          image: k8s-api-proxy:latest
          imagePullPolicy: Never
          command: ["kubectl","proxy","--port=8080"]
          resources:
            requests:
              cpu: "100m"
              memory: "56Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
        - name: monitor
          image: monitor:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: JAVA_OPTS
              value: '-Xms128m -Xmx256m -XX:MaxMetaspaceSize=64m -Djdk.tls.client.protocols=TLSv1.2'              
          ports:
            - containerPort: 5959
