apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplecache
spec:
  selector:
    matchLabels:
      app: simplecache
  replicas: 3
  template:
    metadata:
      labels:
        app: simplecache
    spec:
      containers:
        - name: server
          image: server:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "256Mi"
          ports:
            - containerPort: 5959
        - name: proxycontainer
          image: k8s-api-proxy:latest
          imagePullPolicy: Never
          command: ["kubectl","proxy","--port=8080"]
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
        - name: monitor
          image: monitor:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: JAVA_OPTS
              value: '-Xms128m -Xmx256m -XX:MaxMetaspaceSize=64m -Djdk.tls.client.protocols=TLSv1.2'
          ports:
            - containerPort: 5959
