apiVersion: v1
kind: Service
metadata:
  name: simplecache
  labels:
    app: simplecache
spec:
  type: NodePort
  selector:
    app: simplecache
  ports:
    - name: tcp
      protocol: TCP
      port: 5959
      targetPort: 5959
